/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Health */
        readonly get: operations["getHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/models": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Models */
        readonly get: operations["getModels"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/active-model": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /**
         * Set Active Model
         * @description Switch the active model: `409 cannot_be_active` for a model that is unavailable or not
         *     evaluated. The live monitor is told, and its next frame is judged by the new model.
         */
        readonly put: operations["setActiveModel"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/persons": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Persons */
        readonly get: operations["listPersons"];
        readonly put?: never;
        /** Create Person */
        readonly post: operations["createPerson"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/persons/{person_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Person */
        readonly get: operations["getPerson"];
        readonly put?: never;
        readonly post?: never;
        /**
         * Purge Person
         * @description Purge a person of interest, on the watchlist or removed: their enrolled photos,
         *     embeddings and sightings are erased, and they are cleared as runner-up on other sightings.
         *     Not reversible.
         */
        readonly delete: operations["purgePerson"];
        readonly options?: never;
        readonly head?: never;
        /**
         * Update Person
         * @description Rename, remove or restore a person of interest; an empty body changes nothing. Removal
         *     takes them off the watchlist the live monitor matches against from its next frame.
         */
        readonly patch: operations["updatePerson"];
        readonly trace?: never;
    };
    readonly "/api/persons/{person_id}/photos": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Add Photo */
        readonly post: operations["addPhoto"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/persons/{person_id}/photos/{photo_id}/image": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Photo Image */
        readonly get: operations["getPhotoImage"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/persons/{person_id}/photos/{photo_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /** Delete Photo */
        readonly delete: operations["deletePhoto"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActiveModelChoice
         * @description The model to make active. Any other field, such as a threshold, is refused with
         *     `422 invalid_request`: thresholds come from evaluation only.
         */
        readonly ActiveModelChoice: {
            /** Modelkey */
            readonly modelKey: string;
        };
        /** Body_addPhoto */
        readonly Body_addPhoto: {
            /** Photo */
            readonly photo: string;
            /** Acknowledgedwarnings */
            readonly acknowledgedWarnings?: readonly components["schemas"]["WarningCode"][];
        };
        /** Body_createPerson */
        readonly Body_createPerson: {
            /** Name */
            readonly name: string;
            /** Photo */
            readonly photo: string;
            /** Acknowledgedwarnings */
            readonly acknowledgedWarnings?: readonly components["schemas"]["WarningCode"][];
        };
        /** EnrolledPhoto */
        readonly EnrolledPhoto: {
            /** Id */
            readonly id: string;
            /** Mediatype */
            readonly mediaType: string;
            /** Width */
            readonly width: number;
            /** Height */
            readonly height: number;
            /**
             * Createdat
             * Format: date-time
             */
            readonly createdAt: string;
        };
        /** Health */
        readonly Health: {
            /**
             * Status
             * @constant
             */
            readonly status: "ok";
            /** Version */
            readonly version: string;
        };
        /** @enum {string} */
        readonly ModelState: "active" | "available" | "not_evaluated" | "unavailable";
        /** @enum {string} */
        readonly Network: "arcface" | "facenet" | "sface";
        /** PersonOfInterest */
        readonly PersonOfInterest: {
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
            readonly status: components["schemas"]["PersonStatus"];
            /**
             * Createdat
             * Format: date-time
             */
            readonly createdAt: string;
            /**
             * Statuschangedat
             * Format: date-time
             */
            readonly statusChangedAt: string;
            /** Photos */
            readonly photos: readonly components["schemas"]["EnrolledPhoto"][];
        };
        /**
         * PersonOfInterestChanges
         * @description What PATCH changes: the name, the status, both or neither. A field left out is left as it
         *     is; null, or any other field such as `statusChangedAt`, is refused with
         *     `422 invalid_request` rather than ignored.
         */
        readonly PersonOfInterestChanges: {
            /** Name */
            readonly name?: string;
            /** Status */
            readonly status?: components["schemas"]["PersonStatus"];
        };
        /** PersonOfInterestSummary */
        readonly PersonOfInterestSummary: {
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
            readonly status: components["schemas"]["PersonStatus"];
            /** Photocount */
            readonly photoCount: number;
            /** Coverphotoid */
            readonly coverPhotoId: string;
            /**
             * Createdat
             * Format: date-time
             */
            readonly createdAt: string;
            /**
             * Statuschangedat
             * Format: date-time
             */
            readonly statusChangedAt: string;
        };
        /** @enum {string} */
        readonly PersonStatus: "on_watchlist" | "removed";
        /** @enum {string} */
        readonly Provider: "cpu" | "coreml";
        /** RecognitionModelInfo */
        readonly RecognitionModelInfo: {
            /** Id */
            readonly id: string;
            readonly network: components["schemas"]["Network"];
            readonly provider: components["schemas"]["Provider"];
            /** Weightssha256 */
            readonly weightsSha256: string;
            /** Name */
            readonly name: string;
            readonly state: components["schemas"]["ModelState"];
            /** Threshold */
            readonly threshold: number | null;
            /** Dimension */
            readonly dimension: number;
            /** Msperface */
            readonly msPerFace: number | null;
        };
        /** @enum {string} */
        readonly WarningCode: "duplicate_name" | "looks_like_other" | "may_not_be_same_person";
        /**
         * ActiveModelChanged
         * @description The active model was switched; the next frame's result is judged by it.
         */
        readonly ActiveModelChanged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "active_model_changed";
            /** Modelkey */
            readonly modelKey: string;
            /** Threshold */
            readonly threshold: number;
        };
        /** EnrollmentWarning */
        readonly EnrollmentWarning: {
            readonly code: components["schemas"]["WarningCode"];
            /** Detail */
            readonly detail: string;
            /** Personid */
            readonly personId: string | null;
        };
        readonly Face: components["schemas"]["MatchFace"] | components["schemas"]["NoMatchFace"] | components["schemas"]["TooSmallFace"];
        /**
         * FaceBox
         * @description A face's box in the pixels of the frame it was found in. Not clipped to the frame.
         */
        readonly FaceBox: {
            /** X */
            readonly x: number;
            /** Y */
            readonly y: number;
            /** Width */
            readonly width: number;
            /** Height */
            readonly height: number;
        };
        /**
         * FrameResult
         * @description Every face in one frame, judged by the active model at its threshold.
         */
        readonly FrameResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "result";
            /** Seq */
            readonly seq: number;
            /** Capturedat */
            readonly capturedAt: number;
            /** Width */
            readonly width: number;
            /** Height */
            readonly height: number;
            /** Modelkey */
            readonly modelKey: string;
            /** Threshold */
            readonly threshold: number;
            /** Faces */
            readonly faces: readonly components["schemas"]["Face"][];
        };
        /** MatchFace */
        readonly MatchFace: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly outcome: "match";
            readonly box: components["schemas"]["FaceBox"];
            /** Score */
            readonly score: number;
            readonly person: components["schemas"]["MatchedPerson"];
        };
        /** MatchedPerson */
        readonly MatchedPerson: {
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
        };
        /**
         * MonitorError
         * @description A message that could not be used as a frame, or a frame whose recognition failed
         *     unexpectedly (`internal_error`). The connection stays open.
         */
        readonly MonitorError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "error";
            /** Seq */
            readonly seq: number | null;
            /** Code */
            readonly code: string;
            /** Detail */
            readonly detail: string;
        };
        /**
         * MonitorMessage
         * @description Every message the service sends on `/api/monitor`, by `type`.
         */
        readonly MonitorMessage: components["schemas"]["FrameResult"] | components["schemas"]["ActiveModelChanged"] | components["schemas"]["MonitorError"];
        /** NoMatchFace */
        readonly NoMatchFace: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly outcome: "no_match";
            readonly box: components["schemas"]["FaceBox"];
            /** Score */
            readonly score: number | null;
        };
        /**
         * Problem
         * @description An RFC 9457 problem detail with Ryuk's `code` extension.
         */
        readonly Problem: {
            /** Type */
            readonly type: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: number;
            /** Detail */
            readonly detail: string;
            /** Code */
            readonly code: string;
        };
        /**
         * TooSmallFace
         * @description A detection too small to use: never scored.
         */
        readonly TooSmallFace: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly outcome: "too_small";
            readonly box: components["schemas"]["FaceBox"];
        };
        /**
         * WarningsProblem
         * @description `409 warnings`: resend with every listed code in `acknowledgedWarnings` to proceed.
         */
        readonly WarningsProblem: {
            /** Type */
            readonly type: string;
            /** Title */
            readonly title: string;
            /** Status */
            readonly status: number;
            /** Detail */
            readonly detail: string;
            /** Code */
            readonly code: string;
            /** Warnings */
            readonly warnings: readonly components["schemas"]["EnrollmentWarning"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly getHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly getModels: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["RecognitionModelInfo"][];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly setActiveModel: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ActiveModelChoice"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RecognitionModelInfo"];
                };
            };
            /** @description Invalid request */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly listPersons: {
        readonly parameters: {
            readonly query?: {
                readonly status?: "on_watchlist" | "removed" | "all";
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["PersonOfInterestSummary"][];
                };
            };
            /** @description Invalid request */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly createPerson: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": components["schemas"]["Body_createPerson"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PersonOfInterest"];
                };
            };
            /** @description Warnings to acknowledge */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["WarningsProblem"];
                };
            };
            /** @description Invalid request */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly getPerson: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly person_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PersonOfInterest"];
                };
            };
            /** @description Invalid request */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly purgePerson: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly person_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly updatePerson: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly person_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PersonOfInterestChanges"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PersonOfInterest"];
                };
            };
            /** @description Invalid request */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly addPhoto: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly person_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": components["schemas"]["Body_addPhoto"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["EnrolledPhoto"];
                };
            };
            /** @description Warnings to acknowledge */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["WarningsProblem"];
                };
            };
            /** @description Invalid request */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly getPhotoImage: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly person_id: string;
                readonly photo_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The enrolled photo, upright and without metadata */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "image/jpeg": unknown;
                    readonly "image/png": unknown;
                    readonly "image/webp": unknown;
                };
            };
            /** @description Invalid request */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readonly deletePhoto: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly person_id: string;
                readonly photo_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Problem */
            readonly default: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
