/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as EvaluationRouteImport } from "./routes/evaluation";
import { Route as MonitorRouteImport } from "./routes/monitor";
import { Route as SightingsIndexRouteImport } from "./routes/sightings/index";
import { Route as SightingsSightingIdRouteImport } from "./routes/sightings/$sightingId";
import { Route as WatchlistIndexRouteImport } from "./routes/watchlist/index";
import { Route as WatchlistPersonIdRouteImport } from "./routes/watchlist/$personId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const EvaluationRoute = EvaluationRouteImport.update({
  id: "/evaluation",
  path: "/evaluation",
  getParentRoute: () => rootRouteImport,
} as any);
const MonitorRoute = MonitorRouteImport.update({
  id: "/monitor",
  path: "/monitor",
  getParentRoute: () => rootRouteImport,
} as any);
const SightingsIndexRoute = SightingsIndexRouteImport.update({
  id: "/sightings/",
  path: "/sightings/",
  getParentRoute: () => rootRouteImport,
} as any);
const SightingsSightingIdRoute = SightingsSightingIdRouteImport.update({
  id: "/sightings/$sightingId",
  path: "/sightings/$sightingId",
  getParentRoute: () => rootRouteImport,
} as any);
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: "/watchlist/",
  path: "/watchlist/",
  getParentRoute: () => rootRouteImport,
} as any);
const WatchlistPersonIdRoute = WatchlistPersonIdRouteImport.update({
  id: "/watchlist/$personId",
  path: "/watchlist/$personId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/evaluation": typeof EvaluationRoute;
  "/monitor": typeof MonitorRoute;
  "/sightings/$sightingId": typeof SightingsSightingIdRoute;
  "/watchlist/$personId": typeof WatchlistPersonIdRoute;
  "/sightings/": typeof SightingsIndexRoute;
  "/watchlist/": typeof WatchlistIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/evaluation": typeof EvaluationRoute;
  "/monitor": typeof MonitorRoute;
  "/sightings/$sightingId": typeof SightingsSightingIdRoute;
  "/watchlist/$personId": typeof WatchlistPersonIdRoute;
  "/sightings": typeof SightingsIndexRoute;
  "/watchlist": typeof WatchlistIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/evaluation": typeof EvaluationRoute;
  "/monitor": typeof MonitorRoute;
  "/sightings/$sightingId": typeof SightingsSightingIdRoute;
  "/watchlist/$personId": typeof WatchlistPersonIdRoute;
  "/sightings/": typeof SightingsIndexRoute;
  "/watchlist/": typeof WatchlistIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/evaluation"
    | "/monitor"
    | "/sightings/$sightingId"
    | "/watchlist/$personId"
    | "/sightings/"
    | "/watchlist/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/evaluation"
    | "/monitor"
    | "/sightings/$sightingId"
    | "/watchlist/$personId"
    | "/sightings"
    | "/watchlist";
  id:
    | "__root__"
    | "/"
    | "/evaluation"
    | "/monitor"
    | "/sightings/$sightingId"
    | "/watchlist/$personId"
    | "/sightings/"
    | "/watchlist/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  EvaluationRoute: typeof EvaluationRoute;
  MonitorRoute: typeof MonitorRoute;
  SightingsSightingIdRoute: typeof SightingsSightingIdRoute;
  WatchlistPersonIdRoute: typeof WatchlistPersonIdRoute;
  SightingsIndexRoute: typeof SightingsIndexRoute;
  WatchlistIndexRoute: typeof WatchlistIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/evaluation": {
      id: "/evaluation";
      path: "/evaluation";
      fullPath: "/evaluation";
      preLoaderRoute: typeof EvaluationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/monitor": {
      id: "/monitor";
      path: "/monitor";
      fullPath: "/monitor";
      preLoaderRoute: typeof MonitorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sightings/": {
      id: "/sightings/";
      path: "/sightings";
      fullPath: "/sightings/";
      preLoaderRoute: typeof SightingsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sightings/$sightingId": {
      id: "/sightings/$sightingId";
      path: "/sightings/$sightingId";
      fullPath: "/sightings/$sightingId";
      preLoaderRoute: typeof SightingsSightingIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/watchlist/": {
      id: "/watchlist/";
      path: "/watchlist";
      fullPath: "/watchlist/";
      preLoaderRoute: typeof WatchlistIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/watchlist/$personId": {
      id: "/watchlist/$personId";
      path: "/watchlist/$personId";
      fullPath: "/watchlist/$personId";
      preLoaderRoute: typeof WatchlistPersonIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationRoute: EvaluationRoute,
  MonitorRoute: MonitorRoute,
  SightingsSightingIdRoute: SightingsSightingIdRoute,
  WatchlistPersonIdRoute: WatchlistPersonIdRoute,
  SightingsIndexRoute: SightingsIndexRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
